#!/usr/bin/env bash

TO_DATE=$(date +%d-%m-%Y -d "$DATE + 30 day")
DATE=$(date +%d-%m-%Y)
LAT=$1 #-6.2088
LON=$2 #106.8456
refresh=$3 #refresh interval
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JSON_FILE="prayer_times_monthly.json"
STORED_INDEX=null

# Function to fetch data
URL="https://api.aladhan.com/v1/calendar/from/${DATE}/to/${TO_DATE}?latitude=${LAT}&longitude=${LON}"
JSON_PATH="$SCRIPT_DIR/$JSON_FILE"

fetch_data() {
    # notify-send "Requesting data" "$URL"
    dms ipc toast infoWith 'Requesting data' "$URL" '' ''
    curl -s "$URL" | jq '.' > "$JSON_PATH"
    dms ipc toast infoWith 'Saved json' "from ${DATE} to ${TO_DATE}" '' ''
    # notify-send "Saved json" "from ${DATE} to ${TO_DATE}"
}

get_stored_index() {
    jq --arg date "$DATE" \
       '.data | map(.date.gregorian.date == $date) | index(true)' \
       "$JSON_PATH"
}

# Fetch if file missing OR date not found
if [ ! -f "$JSON_PATH" ] || [ "$(get_stored_index)" = "null" ]; then
    fetch_data
fi

STORED_INDEX="$(get_stored_index)"

# Read timings from JSON
TODAYDATA=$(jq --argjson i "$STORED_INDEX" '.data[$i]' "$JSON_PATH")
if [ -z "$TODAYDATA" ] || [ "$TODAYDATA" == "null" ]; then
    echo "Error fetching prayer times"
    exit 1
fi

TIMINGS=$(echo "$TODAYDATA" | jq -r '.timings')
FAJR=$(echo "$TIMINGS" | jq -r '.Fajr')
DHUHR=$(echo "$TIMINGS" | jq -r '.Dhuhr')
ASR=$(echo "$TIMINGS" | jq -r '.Asr')
MAGHRIB=$(echo "$TIMINGS" | jq -r '.Maghrib')
ISHA=$(echo "$TIMINGS" | jq -r '.Isha')
NOW=$(date +%H:%M)
SUNRISE=$(echo "$TIMINGS" | jq -r '.Sunrise')

GREG_DATE=$(echo "$TODAYDATA" | jq -r '.date.readable')
HIJRI_DATE=$(echo "$TODAYDATA" | jq -r '.date.hijri | "\(.day) \(.month.en) \(.year)"')

# echo $GREG_DATE
# exit 1

# Fungsi untuk mengubah HH:MM ke total menit
to_minutes() {
    echo "$1" | awk -F: '{ print ($1 * 60) + $2 }'
}

NOW_MIN=$(to_minutes "$NOW")
if [[ "$NOW" < "$FAJR" ]]; then
    CURR_NAME="Isha";    CURR_TIME="$ISHA"
    NEXT_NAME="Fajr";    NEXT_TIME="$FAJR"
elif [[ "$NOW" < "$SUNRISE" ]]; then
    CURR_NAME="Fajr";    CURR_TIME="$FAJR"
    NEXT_NAME="Sunrise"; NEXT_TIME="$SUNRISE"
elif [[ "$NOW" < "$DHUHR" ]]; then
    CURR_NAME="Sunrise"; CURR_TIME="$SUNRISE"
    NEXT_NAME="Dhuhr";   NEXT_TIME="$DHUHR"
elif [[ "$NOW" < "$ASR" ]]; then
    CURR_NAME="Dhuhr";   CURR_TIME="$DHUHR"
    NEXT_NAME="Asr";     NEXT_TIME="$ASR"
elif [[ "$NOW" < "$MAGHRIB" ]]; then
    CURR_NAME="Asr";     CURR_TIME="$ASR"
    NEXT_NAME="Maghrib"; NEXT_TIME="$MAGHRIB"
elif [[ "$NOW" < "$ISHA" ]]; then
    CURR_NAME="Maghrib"; CURR_TIME="$MAGHRIB"
    NEXT_NAME="Isha";    NEXT_TIME="$ISHA"
else
    CURR_NAME="Isha";    CURR_TIME="$ISHA"
    NEXT_NAME="Fajr";    NEXT_TIME="$FAJR"
fi

# Hitung selisih antara NOW dengan waktu shalat yang sedang berjalan (CURR_TIME)
CURR_MIN=$(to_minutes "$CURR_TIME")
SELISIH=$(( NOW_MIN - CURR_MIN ))

# Koreksi jika menyeberang hari (misal: NOW 00:10, Isha kemarin 19:20)
if [ $SELISIH -lt 0 ]; then
    SELISIH=$(( SELISIH + 1440 ))
fi

# Logika Tampilan: Jika selisih masih dalam 30 menit
if (( SELISIH <= 30 )); then
    ALERT="$CURR_NAME ${CURR_TIME:0:5}"
    RESULT="Current: $ALERT - "
    if (( SELISIH - 1 <= refresh / 60000 )); then 
        dms ipc toast info "Prayer time - $ALERT"
    fi
fi

RESULT+="Next: $NEXT_NAME ${NEXT_TIME:0:5}"

TIMINGS=$(echo "$TIMINGS" | jq \
  --arg prayerInfo "$RESULT" \
  --arg hijr "$HIJRI_DATE" \
  --arg greg "$GREG_DATE" \
  --arg currName "$CURR_NAME" \
  '. + {prayerInfo: $prayerInfo, DateHijr: $hijr, DateGreg: $greg, currName: $currName}')
  
TIMINGSS=$(echo "$TIMINGS" | jq -c .)
echo "$TIMINGSS"

# try to calling fetch data when the json hasn't updated for 10 days event the json still has the valid date
if [[ "$STORED_INDEX" =~ ^[0-9]+$ ]] && [ "$STORED_INDEX" -gt 10 ]; then
    fetch_data
fi